[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mushi_stake_vault = "Bne2XHWW1HaMVHp6jXmCcmX3dVrtFMoYV5n2eyrvFw46"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/init.ts"
stake = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/stake.ts"
unstake = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/unstake.ts"
getStats = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/getStats.ts"
